#Array holding list of 100 most populated US cities
cities = [
	"NY - New York",
	"CA - Los Angeles",
	"IL - Chicago",
	"NY - Brooklyn",
	"NY - Queens",
	"TX - Houston",
	"NY - Manhattan",
	"PA - Philadelphia",
	"AZ - Phoenix",
	"TX - San Antonio",
	"NY - Bronx",
	"CA - San Diego",
	"TX - Dallas",
	"CA - San Jose",
	"CA - East San Gabriel Valley",
	"TX - Austin",
	"FL - Jacksonville",
	"CA - San Francisco",
	"IN - Indianapolis",
	"OH - Columbus",
	"TX - Fort Worth",
	"NC - Charlotte",
	"MI - Detroit",
	"TX - El Paso",
	"WA - Seattle",
	"CO - Denver",
	"DC - Washington",
	"TN - Memphis",
	"MA - Boston",
	"TN - Nashville-Davidson",
	"MD - Baltimore",
	"TN - Metropolitan Government",
	"OK - Oklahoma City",
	"OR - Portland",
	"NV - Las Vegas",
	"WI - Milwaukee",
	"NM - Albuquerque",
	"AZ - Tucson",
	"CA - Fresno",
	"WA - East Seattle",
	"CA - Central Contra Costa",
	"CA - Sacramento",
	"NY - Staten Island",
	"CA - Long Beach",
	"TX - Northeast Tarrant",
	"MO - Kansas City",
	"AZ - Mesa",
	"TX - Northwest Harris",
	"GA - Atlanta",
	"CO - Northeast Jefferson",
	"VA - Virginia Beach",
	"NE - Omaha",
	"CO - Colorado Springs",
	"NC - Raleigh",
	"FL - Miami",
	"CA - Oakland",
	"MN - Minneapolis",
	"OK - Tulsa",
	"OH - Cleveland",
	"KS - Wichita",
	"LA - New Orleans",
	"TX - Arlington",
	"CA - North Coast",
	"HI - Honolulu",
	"CA - Bakersfield",
	"FL - Tampa",
	"CO - Aurora",
	"HI - Urban Honolulu",
	"CA - Anaheim",
	"FL - Kendale Lakes-Lindgren Acres",
	"CA - Santa Ana",
	"CO - South Aurora",
	"CA - Upper San Gabriel Valley",
	"CA - Southwest San Gabriel Valley",
	"TX - Corpus Christi",
	"CA - Riverside",
	"MO - St. Louis",
	"KY - Lexington-Fayette",
	"CO - West Adams",
	"PA - Pittsburgh",
	"CA - Stockton",
	"AK - Anchorage",
	"CA - South Coast",
	"OH - Cincinnati",
	"MN - St. Paul",
	"TX - Southeast Montgomery",
	"KY - Fayette",
	"NC - Greensboro",
	"OH - Toledo",
	"NJ - Newark",
	"HI - Ewa",
	"TX - Plano",
	"NV - Henderson",
	"NE - Lincoln",
	"KY - Louisville",
	"FL - Orlando",
	"NJ - Jersey City",
	"CA - Chula Vista",
	"NY - Buffalo",
	"IN - Fort Wayne"
]

#Function to format city string for Wunderground weather API
def format_city_for_api( string ):
    x = string.split( " - ", 1)
    city = x[1]
    city = city.replace(' ', '_')
    y = x[0] + '/' + city
    return y

#Format the cities
cities_formatted = []
for city in cities:
	api_formatted_city = format_city_for_api( city )
	cities_formatted.append( (api_formatted_city, city) )
cities = cities_formatted