# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-06 00:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='location',
            field=models.CharField(default=datetime.datetime(2016, 12, 6, 0, 49, 56, 407027, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
    ]
