# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-08 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_auto_20161205_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='location',
            field=models.CharField(choices=[('NY - New York', '02072'), ('CA - Los Angeles', '02072'), ('IL - Chicago', '02072'), ('NY - Brooklyn', '02072'), ('NY - Queens', '02072'), ('TX - Houston', '02072'), ('NY - Manhattan', '02072'), ('PA - Philadelphia', '02072'), ('AZ - Phoenix', '02072'), ('TX - San Antonio', '02072'), ('NY - Bronx', '02072'), ('CA - San Diego', '02072'), ('TX - Dallas', '02072'), ('CA - San Jose', '02072'), ('CA - East San Gabriel Valley', '02072'), ('TX - Austin', '02072'), ('FL - Jacksonville', '02072'), ('CA - San Francisco', '02072'), ('IN - Indianapolis', '02072'), ('OH - Columbus', '02072'), ('TX - Fort Worth', '02072'), ('NC - Charlotte', '02072'), ('MI - Detroit', '02072'), ('TX - El Paso', '02072'), ('WA - Seattle', '02072'), ('CO - Denver', '02072'), ('DC - Washington', '02072'), ('TN - Memphis', '02072'), ('MA - Boston', '02072'), ('TN - Nashville-Davidson', '02072'), ('MD - Baltimore', '02072'), ('TN - Metropolitan Government', '02072'), ('OK - Oklahoma City', '02072'), ('OR - Portland', '02072'), ('NV - Las Vegas', '02072'), ('WI - Milwaukee', '02072'), ('NM - Albuquerque', '02072'), ('AZ - Tucson', '02072'), ('CA - Fresno', '02072'), ('WA - East Seattle', '02072'), ('CA - Central Contra Costa', '02072'), ('CA - Sacramento', '02072'), ('NY - Staten Island', '02072'), ('CA - Long Beach', '02072'), ('TX - Northeast Tarrant', '02072'), ('MO - Kansas City', '02072'), ('AZ - Mesa', '02072'), ('TX - Northwest Harris', '02072'), ('GA - Atlanta', '02072'), ('CO - Northeast Jefferson', '02072'), ('VA - Virginia Beach', '02072'), ('NE - Omaha', '02072'), ('CO - Colorado Springs', '02072'), ('NC - Raleigh', '02072'), ('FL - Miami', '02072'), ('CA - Oakland', '02072'), ('MN - Minneapolis', '02072'), ('OK - Tulsa', '02072'), ('OH - Cleveland', '02072'), ('KS - Wichita', '02072'), ('LA - New Orleans', '02072'), ('TX - Arlington', '02072'), ('CA - North Coast', '02072'), ('HI - Honolulu', '02072'), ('CA - Bakersfield', '02072'), ('FL - Tampa', '02072'), ('CO - Aurora', '02072'), ('HI - Urban Honolulu', '02072'), ('CA - Anaheim', '02072'), ('FL - Kendale Lakes-Lindgren Acres', '02072'), ('CA - Santa Ana', '02072'), ('CO - South Aurora', '02072'), ('CA - Upper San Gabriel Valley', '02072'), ('CA - Southwest San Gabriel Valley', '02072'), ('TX - Corpus Christi', '02072'), ('CA - Riverside', '02072'), ('MO - St. Louis', '02072'), ('KY - Lexington-Fayette', '02072'), ('CO - West Adams', '02072'), ('PA - Pittsburgh', '02072'), ('CA - Stockton', '02072'), ('AK - Anchorage', '02072'), ('CA - South Coast', '02072'), ('OH - Cincinnati', '02072'), ('MN - St. Paul', '02072'), ('TX - Southeast Montgomery', '02072'), ('KY - Fayette', '02072'), ('NC - Greensboro', '02072'), ('OH - Toledo', '02072'), ('NJ - Newark', '02072'), ('HI - Ewa', '02072'), ('TX - Plano', '02072'), ('NV - Henderson', '02072'), ('NE - Lincoln', '02072'), ('KY - Louisville', '02072'), ('FL - Orlando', '02072'), ('NJ - Jersey City', '02072'), ('CA - Chula Vista', '02072'), ('NY - Buffalo', '02072'), ('IN - Fort Wayne', '02072')], max_length=5),
        ),
    ]
