# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-12 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0006_auto_20170311_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='location',
            field=models.CharField(max_length=250),
        ),
    ]
